# Generated by Django 4.1.2 on 2023-01-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_myuser_interest_usergenres_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authormessages',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bookmessages',
            name='id',
        ),
        migrations.RemoveField(
            model_name='forummessages',
            name='id',
        ),
        migrations.AlterField(
            model_name='authormessages',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.author'),
        ),
        migrations.AlterField(
            model_name='bookmessages',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.book'),
        ),
        migrations.AlterField(
            model_name='forummessages',
            name='forum_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.forum'),
        ),
    ]
