# Generated by Django 4.1.2 on 2023-01-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_authormessages_id_remove_bookmessages_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormessages',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.author', unique=True),
        ),
        migrations.AlterField(
            model_name='bookmessages',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.book', unique=True),
        ),
        migrations.AlterField(
            model_name='forummessages',
            name='forum_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.forum', unique=True),
        ),
    ]
