# Generated by Django 4.1.2 on 2023-02-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_myuser_recommended_booktracker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booktracker',
            unique_together={('book', 'user')},
        ),
    ]
