# Generated by Django 4.1.2 on 2023-02-14 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_forumtab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authormessages',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='authormessages',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='bookmessages',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookmessages',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='forummessages',
            old_name='forum_id',
            new_name='forum',
        ),
        migrations.RenameField(
            model_name='forummessages',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user_id',
        ),
        migrations.AddField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
