# Generated by Django 4.1.2 on 2023-01-17 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_myuser_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='interest',
        ),
        migrations.AddField(
            model_name='usergenres',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
