# Generated by Django 4.1.2 on 2023-01-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_authormessages_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormessages',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmessages',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forummessages',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authormessages',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.author'),
        ),
        migrations.AlterField(
            model_name='bookmessages',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.book'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='forummessages',
            name='forum_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.forum'),
        ),
    ]
