# Generated by Django 4.1.2 on 2023-02-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
