# Generated by Django 4.1.2 on 2023-02-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_forumtab_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtab',
            name='name',
            field=models.CharField(max_length=54),
        ),
    ]
