# Generated by Django 4.1.2 on 2023-02-16 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_forumtab_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreviews',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='User', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Friend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
