# Generated by Django 4.1.2 on 2023-02-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_bookreviews_rating_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
