# Generated by Django 4.1.2 on 2022-11-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='DateOfBirth',
            field=models.DateField(default='1970-1-1'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='ProfilePicture',
            field=models.ImageField(default='defaultIcon.jpg', upload_to='uploads'),
        ),
    ]
