# Generated by Django 4.1.2 on 2022-12-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_myuser_dateofbirth_myuser_profilepicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='DateOfBirth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='ProfilePicture',
            new_name='profilePicture',
        ),
    ]
