# Generated by Django 4.1.2 on 2022-12-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_dateofbirth_myuser_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(default='city', max_length=50),
        ),
    ]
