# Generated by Django 4.1.2 on 2022-12-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_myuser_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_picture', models.ImageField(upload_to='uploads/items')),
                ('auction_finish', models.DateField()),
                ('item_owner', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='dateOfBirth',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='profilePicture',
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(default='defaultIcon.jpg', upload_to='uploads/users'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
