# Generated by Django 4.1.2 on 2022-12-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_auctionitem_auction_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
